//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class alternativeContact
    {
        public int Code { get; set; }
        public string ContactKeyEmail { get; set; }
        public Nullable<int> alternativeType { get; set; }
        public string alternativeName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}
