//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_CV
    {
        public int Code { get; set; }
        public int ContactCode { get; set; }
        public string Field_1 { get; set; }
        public string Field_2 { get; set; }
        public string Field_3 { get; set; }
        public string Field_4 { get; set; }
        public string Field_5 { get; set; }
        public string Field_6 { get; set; }
        public string Field_7 { get; set; }
        public string Field_8 { get; set; }
        public string Field_9 { get; set; }
        public string Field_10 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> RCCYN { get; set; }
        public string RegionalCountriesArabicName { get; set; }
        public string RegionalCountriesEnglishName { get; set; }
        public string InternationalCountriesArabicName { get; set; }
        public string InternationalCountriesEnglishName { get; set; }
        public string LanguageArabicName { get; set; }
        public string LanguageEnglishName { get; set; }
        public string SpecialExpertiseInfo { get; set; }
    }
}
