//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int Code { get; set; }
        public Nullable<int> Taxes { get; set; }
        public Nullable<int> RiseCommission { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
