//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturedExpertiseLog
    {
        public int Code { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public string Relations { get; set; }
        public string TypeOfExpertise { get; set; }
        public string DurationOfExpertise { get; set; }
        public string LevelOfExpertise { get; set; }
        public string PublicPerson { get; set; }
        public string FoundOnline { get; set; }
        public string Title { get; set; }
        public string SpecialRecogination { get; set; }
        public string Other { get; set; }
        public string Info { get; set; }
        public Nullable<int> RCLCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
