//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FielsUpload
    {
        public int Code { get; set; }
        public string FileID { get; set; }
        public string FileSize { get; set; }
        public string FolderName { get; set; }
        public Nullable<int> FileTypeCode { get; set; }
        public string PathFileLocal { get; set; }
        public string PathFileServer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserID { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> PrimaryCheckYN { get; set; }
        public Nullable<bool> SecondCheckYN { get; set; }
        public Nullable<bool> BuyCheckYN { get; set; }
        public Nullable<bool> FreezeYN { get; set; }
        public Nullable<bool> ApproveYN { get; set; }
        public Nullable<double> FileSizeBybyte { get; set; }
        public Nullable<System.DateTime> UploadFileDate { get; set; }
        public string CheckerName { get; set; }
        public Nullable<System.DateTime> CheckerDate { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<bool> RegionalYN { get; set; }
        public Nullable<bool> InternationalYN { get; set; }
        public Nullable<bool> GloabalYN { get; set; }
        public Nullable<bool> CompleteYN { get; set; }
        public Nullable<bool> InCompleteYN { get; set; }
        public Nullable<bool> CloseYN { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public Nullable<bool> OnlineFormYN { get; set; }
        public Nullable<bool> SpecialExpertiseFirstYN { get; set; }
        public Nullable<bool> SpecialExpertiseSecondYN { get; set; }
        public Nullable<bool> SpecialExpertiseYN { get; set; }
        public Nullable<bool> ApproveSpecialYN { get; set; }
    }
}
