//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinsStatement
    {
        public int Code { get; set; }
        public int TransactionCode { get; set; }
        public int UserCode { get; set; }
        public string UserRole { get; set; }
        public string PaymentType { get; set; }
        public string Cr_Dr { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> RiseCommission { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string MerchantCode { get; set; }
        public string MerchantRefNum { get; set; }
        public Nullable<int> CustomerProfileId { get; set; }
        public string CardToken { get; set; }
        public string CardLast4digits { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerEmail { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string Description { get; set; }
        public string PaymentExpiry { get; set; }
        public string ChargeItems_ItemID { get; set; }
        public Nullable<decimal> ChargeItems_Price { get; set; }
        public Nullable<int> ChargeItems_Quantity { get; set; }
        public string ChargeItems_Description { get; set; }
        public string Signature { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> CardCharge_StatusCode { get; set; }
        public string CardCharge_StatusDescription { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string StatusDescription { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TransactionTypes { get; set; }
    }
}
