//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermession
    {
        public int Code { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string PageName { get; set; }
        public Nullable<bool> ViewYN { get; set; }
        public Nullable<bool> SaveYN { get; set; }
        public Nullable<bool> DeleteYN { get; set; }
        public Nullable<bool> EditYN { get; set; }
        public string URLPageName { get; set; }
    }
}
