//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_Banks
    {
        public int Code { get; set; }
        public string BankNameAR { get; set; }
        public string BankNameEN { get; set; }
        public int CountryCode { get; set; }
        public bool IsActive { get; set; }
        public string BankCode { get; set; }
    }
}
