//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_Expertises
    {
        public int Code { get; set; }
        public string ExpertiseNameAR { get; set; }
        public string ExpertiseNameEN { get; set; }
        public Nullable<int> ParentExpertiseCode { get; set; }
        public bool IsActive { get; set; }
        public byte[] Photo { get; set; }
        public string ExpertiseDescription { get; set; }
    }
}
