//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_BankBranch
    {
        public int Code { get; set; }
        public string BankBranchNameAR { get; set; }
        public string BankBranchNameEN { get; set; }
        public int BankCode { get; set; }
        public bool IsActive { get; set; }
        public string BranchCode { get; set; }
    }
}
