//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Code { get; set; }
        public string Type { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public string ContactRole { get; set; }
        public Nullable<int> SendingUser { get; set; }
        public Nullable<int> NotificationStatusCode { get; set; }
        public Nullable<int> BookingCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<int> NotificationModBy { get; set; }
        public string NotificationDescriptionEN { get; set; }
        public string NotificationDescriptionAR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
