//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineForm
    {
        public int Code { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string HighSchool { get; set; }
        public string UniversitySchool { get; set; }
        public string University { get; set; }
        public string PostGraduated { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Government { get; set; }
        public string Competencies { get; set; }
        public string Skills { get; set; }
        public string Training { get; set; }
        public string Unions { get; set; }
        public string Clups { get; set; }
        public string Sports { get; set; }
        public string ScientificSocieties { get; set; }
        public string OtherInfo { get; set; }
        public string Qualifications { get; set; }
        public Nullable<int> Languages { get; set; }
    }
}
