//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageInfo
    {
        public int Code { get; set; }
        public string Link1 { get; set; }
        public string Link2 { get; set; }
        public string DescriptionAR { get; set; }
        public string DescriptionEN { get; set; }
        public string field1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PackageType { get; set; }
    }
}
