//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostRV_Questions
    {
        public int Code { get; set; }
        public Nullable<int> RV_Code { get; set; }
        public string Contact_Role { get; set; }
        public Nullable<int> Contact_Code { get; set; }
        public Nullable<int> LOV_Code { get; set; }
        public Nullable<bool> Answer { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
