//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCC_STS
    {
        public int Code { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<int> WorkWorkPlacesCode { get; set; }
        public Nullable<int> ExpertiseCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> WeekNo { get; set; }
    }
}
