//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiseStoredPlace
    {
        public int Code { get; set; }
        public string LocationName { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string Longtiude { get; set; }
        public string Latidiude { get; set; }
        public string LocationAdress { get; set; }
        public string Type { get; set; }
        public Nullable<int> ContactCode { get; set; }
    }
}
