//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV
    {
        public int Code { get; set; }
        public Nullable<int> BookingCode { get; set; }
        public Nullable<bool> RUC_Ready { get; set; }
        public Nullable<bool> RCC_Ready { get; set; }
        public Nullable<System.DateTime> Actual_StartTime { get; set; }
        public Nullable<System.DateTime> Actual_EndTime { get; set; }
        public Nullable<bool> RUC_ReadyToEnd { get; set; }
        public Nullable<bool> RCC_ReadyToEnd { get; set; }
        public string RUC_LastEmotion { get; set; }
        public string RCC_LastEmotion { get; set; }
        public Nullable<bool> Request_Ext10Minutes { get; set; }
        public Nullable<bool> Decline_Ext10Minutes { get; set; }
        public Nullable<bool> Request_ExtHourOrMore { get; set; }
        public Nullable<bool> Decline_ExtHourOrMore { get; set; }
        public Nullable<bool> Extended10Minutes { get; set; }
        public Nullable<bool> ExtendedHourOrMore { get; set; }
        public Nullable<int> RCC_To_RUC_Rating { get; set; }
        public Nullable<int> RUC_To_RCC_Rating { get; set; }
        public Nullable<int> RV_RejectedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ExtendedBookingCode { get; set; }
        public string ExtendedBooking_PaymentLaterOrNow { get; set; }
        public Nullable<int> Extended_NumberOfHours { get; set; }
        public Nullable<decimal> Extended_FeesPerHour { get; set; }
        public Nullable<decimal> Extended_FeesBeforeDiscount { get; set; }
        public Nullable<decimal> Extended_FeesAfterDiscount { get; set; }
        public Nullable<int> RUC_DisputeChoice_LOVCode { get; set; }
        public Nullable<int> RCC_DisputeChoice_LOVCode { get; set; }
        public Nullable<bool> Closed_To_RUC { get; set; }
        public Nullable<bool> Closed_To_RCC { get; set; }
        public Nullable<double> CurrentRCC_Latitude { get; set; }
        public Nullable<double> CurrentRCC_Longtiude { get; set; }
        public Nullable<double> CurrentRUC_Latitude { get; set; }
        public Nullable<double> CurrentRUC_Longtiude { get; set; }
    }
}
