//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialExpertise
    {
        public int Code { get; set; }
        public Nullable<int> ContactCode { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> ExpertiseLevel1 { get; set; }
        public Nullable<int> ExpertiseLevel2 { get; set; }
        public Nullable<int> ExpertiseLevel3 { get; set; }
        public Nullable<int> ExpertiseLevel4 { get; set; }
        public Nullable<decimal> Cost2 { get; set; }
        public Nullable<int> Row2ExpertiseLevel1 { get; set; }
        public Nullable<int> Row2ExpertiseLevel2 { get; set; }
        public Nullable<int> Row2ExpertiseLevel3 { get; set; }
        public Nullable<int> Row2ExpertiseLevel4 { get; set; }
        public Nullable<decimal> Cost3 { get; set; }
        public Nullable<int> Row3ExpertiseLevel1 { get; set; }
        public Nullable<int> Row3ExpertiseLevel2 { get; set; }
        public Nullable<int> Row3ExpertiseLevel3 { get; set; }
        public Nullable<int> Row3ExpertiseLevel4 { get; set; }
        public Nullable<decimal> Cost4 { get; set; }
        public Nullable<int> Row4ExpertiseLevel1 { get; set; }
        public Nullable<int> Row4ExpertiseLevel2 { get; set; }
        public Nullable<int> Row4ExpertiseLevel3 { get; set; }
        public Nullable<int> Row4ExpertiseLevel4 { get; set; }
        public Nullable<decimal> Cost5 { get; set; }
        public Nullable<int> Row5ExpertiseLevel1 { get; set; }
        public Nullable<int> Row5ExpertiseLevel2 { get; set; }
        public Nullable<int> Row5ExpertiseLevel3 { get; set; }
        public Nullable<int> Row5ExpertiseLevel4 { get; set; }
    }
}
