//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sync_Flag
    {
        public int Id { get; set; }
        public Nullable<int> DB_Version { get; set; }
        public Nullable<int> Lookup_Version { get; set; }
    }
}
